AWSTemplateFormatVersion: '2010-09-09'
Description: Backend BTG con FastAPI

Resources:
  BTGInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      SecurityGroups:
        - !Ref BTGSecurityGroup
      KeyName: tu-keypair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3 git
          cd /home/ec2-user
          git clone https://github.com/johnatangomez/btg_backend.git
          cd btg_backend
          python3 -m venv venv_btg
          source venv_btg/bin/activate
          pip install -r requirements.txt
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &

  BTGSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso HTTP al backend
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
